export default {
	TICKET_PRIORITY_LOW : 'low',
	TICKET_PRIORITY_MEDIUM : 'medium',
	TICKET_PRIORITY_HIGH : 'high',
	TICKET_STATUS_OPEN : 'Open',
	TICKET_STATUS_ASSIGNED : 'Assigned',
	TICKET_STATUS_INPROGRESS : 'In progress',
	TICKET_STATUS_REASSIGNED : 'Reassigned',
	TICKET_STATUS_COMPLETED : 'Completed',
	TICKET_STATUS_CANCELLED : 'Cancelled',
	TICKET_PERMISSION_WRITE : 'write',
	TICKET_PERMISSION_READ : 'read',
};